import type { Metadata } from "next";
import Link from "next/link";
import LegalPage from "@/components/LegalPage";
import { getAllLessons } from "@/lib/lessons";

export const metadata: Metadata = {
  title: "About — LearnAComputer",
  description: "What LearnAComputer is, who it is for, and how it is built.",
};

export default function AboutPage() {
  const lessons = getAllLessons();
  const units = new Set(lessons.map((l) => l.unit)).size;
  const activities = lessons.filter(
    (l) => l.playgroundTask.type !== "none" && l.playgroundTask.type !== "placeholder"
  ).length;

  return (
    <LegalPage title="About" updated="27 July 2026">
      <p>
        LearnAComputer teaches basic computer skills to people starting from zero. Not
        &quot;beginner&quot; in the sense of someone who has used computers for years and wants to go
        deeper — beginner in the sense of someone who is not sure what a double-click is.
      </p>

      <h2>How it teaches</h2>
      <p>
        Every skill is taught by doing it. There are{" "}
        <strong>
          {lessons.length} lessons across {units} units, {activities} of them with a hands-on
          activity
        </strong>
        . An activity is never a quiz: you do not pick the right answer from a list, you open the
        file, drag the window, or send the email inside a working simulation of a computer.
      </p>
      <p>
        Recognizing a correct answer and being able to do the thing are different skills, and only
        one of them is useful when you sit down at your own machine.
      </p>

      <h2>One computer</h2>
      <p>
        The practice computer is the same computer in every lesson. The Files app in the first unit
        is the Files app in the third; the browser you meet learning to right-click is the browser
        you use learning to spot a scam. You can open anything in the dock at any time, whether the
        lesson asked you to or not.
      </p>
      <p>
        Nothing you do in it can break anything, and if you get lost there is a Restart button beside
        every activity.
      </p>

      <h2>Then on your own computer</h2>
      <p>
        Practicing in a simulation is safe, and that is also its limitation. Most units therefore end
        with a lesson that names four concrete things to go and do on your real machine — not
        &quot;try it yourself&quot;, which is not an instruction anyone can follow.
      </p>

      <h2>How it is built</h2>
      <p>
        A Next.js site with no database. Lessons are plain JSON files; your progress is a list of
        finished lesson names in your browser&apos;s local storage. There is nothing to sign up for
        and nothing to pay. See <Link href="/privacy">Privacy</Link> for exactly what is stored.
      </p>
      <p>
        The illustrations throughout the site and the photographs inside the practice Photos app are
        generated by a script in the repository rather than licensed from a stock library.
      </p>

      <h2>Dr. Digital</h2>
      <p>
        The character who explains each lesson. Dr. Digital is fictional, has strong opinions about
        pebbles, and once wrote a résumé.
      </p>

      <p className="pt-4">
        <Link href="/lessons">Start the course →</Link>
      </p>
    </LegalPage>
  );
}
