// Generated by scripts/generate-photos.mjs — do not edit by hand.

/**
 * The picture beside a lesson that has no activity. Keyed by lesson slug.
 *
 * `src` animates; `still` is the same drawing holding its finished pose, for
 * learners who have asked for reduced motion. LessonMedia offers both and lets
 * the browser choose — see the note there for why the choice cannot be made
 * inside the SVG.
 */
export const LESSON_ART: Record<string, { src: string; still: string; alt: string; caption?: string }> = {
  "computer-parts-screen": { src: "/lesson/part-screen.svg", still: "/lesson/part-screen-still.svg", alt: "A laptop with the screen outlined" },
  "computer-parts-keyboard": { src: "/lesson/part-keyboard.svg", still: "/lesson/part-keyboard-still.svg", alt: "A laptop with the keyboard outlined" },
  "computer-parts-trackpad": { src: "/lesson/part-trackpad.svg", still: "/lesson/part-trackpad-still.svg", alt: "A laptop with the trackpad outlined" },
  "computer-parts-speakers": { src: "/lesson/part-speakers.svg", still: "/lesson/part-speakers-still.svg", alt: "A laptop with the speaker grilles outlined" },
  "computer-parts-camera": { src: "/lesson/part-camera.svg", still: "/lesson/part-camera-still.svg", alt: "A laptop with the camera above the screen circled" },
  "computer-parts-ports": { src: "/lesson/part-ports.svg", still: "/lesson/part-ports-still.svg", alt: "A laptop with the sockets along its edge outlined" },
  "sleep-laptop": { src: "/lesson/laptop-sleep.svg", still: "/lesson/laptop-sleep-still.svg", alt: "A closed laptop, asleep" },
  "screen-desktop": { src: "/lesson/screen-desktop.svg", still: "/lesson/screen-desktop-still.svg", alt: "A screen with the empty desktop area outlined" },
  "screen-menu-bar": { src: "/lesson/screen-menubar.svg", still: "/lesson/screen-menubar-still.svg", alt: "A screen with the bar across the top outlined" },
  "kb-numbers": { src: "/lesson/key-numbers.svg", still: "/lesson/key-numbers-still.svg", alt: "A keyboard with the row of number keys outlined" },
  "kb-caps-lock": { src: "/lesson/key-caps.svg", still: "/lesson/key-caps-still.svg", alt: "A keyboard with the Caps Lock key outlined" },
  "kb-command": { src: "/lesson/key-ctrl.svg", still: "/lesson/key-ctrl-still.svg", alt: "A keyboard with the Ctrl keys outlined" },
  "kb-escape": { src: "/lesson/key-escape.svg", still: "/lesson/key-escape-still.svg", alt: "A keyboard with the Esc key outlined" },
  "cloud-photos": { src: "/lesson/cloud-backup.svg", still: "/lesson/cloud-backup-still.svg", alt: "Photos rising from a phone into a cloud" },
  "app-vs-website": { src: "/lesson/app-vs-web.svg", still: "/lesson/app-vs-web-still.svg", alt: "App icons on a phone beside a browser window" },
  "hardware-problems": { src: "/lesson/hardware-trouble.svg", still: "/lesson/hardware-trouble-still.svg", alt: "A laptop with a warning sign beside it" },
  "peripheral-problems": { src: "/lesson/peripheral-trouble.svg", still: "/lesson/peripheral-trouble-still.svg", alt: "A mouse whose cable stops short of the socket" },
  "maps-navigation": { src: "/lesson/map-route.svg", still: "/lesson/map-route-still.svg", alt: "A street map with a route between two pins" },
  "qrcodes-siri": { src: "/lesson/qr-code.svg", still: "/lesson/qr-code-still.svg", alt: "A QR code" },
  "shopping-banking": { src: "/lesson/safe-payment.svg", still: "/lesson/safe-payment-still.svg", alt: "A bank card under a closed padlock" },
  "google-docs-share": { src: "/lesson/share-doc.svg", still: "/lesson/share-doc-still.svg", alt: "A document linked to two people" },
  "google-drive-basics": { src: "/lesson/drive-cloud.svg", still: "/lesson/drive-cloud-still.svg", alt: "Folders inside a cloud" },
  "social-media": { src: "/lesson/staying-connected.svg", still: "/lesson/staying-connected-still.svg", alt: "Message bubbles going back and forth" },
  "a11y-why": { src: "/lesson/settings-adapt.svg", still: "/lesson/settings-adapt-still.svg", alt: "A settings panel of sliders and switches" },
  "final-intro": { src: "/lesson/holiday-away.svg", still: "/lesson/holiday-away-still.svg", alt: "A beach with a deckchair and a closed laptop" },
  "final-graduation": { src: "/lesson/graduation.svg", still: "/lesson/graduation-still.svg", alt: "A certificate and a graduation cap" },
  "computer-parts-power-button": { src: "/lesson/power-symbol.svg", still: "/lesson/power-symbol-still.svg", alt: "The power symbol: a circle with a line at the top", caption: "The power symbol looks the same on nearly every device." },
  "computer-parts-charger": { src: "/lesson/charger-cable.svg", still: "/lesson/charger-cable-still.svg", alt: "A charging cable running from a wall plug to a laptop", caption: "This is what a laptop charger looks like." },
};
