// Generated by scripts/generate-photos.mjs — do not edit by hand.

export interface PhotoAsset {
  /** Basename, no extension. */
  id: string;
  src: string;
  label: string;
  w: number;
  h: number;
}

export const PHOTO_ASSETS: PhotoAsset[] = [
  { id: "sunset-beach", src: "/photos/sunset-beach.webp", label: "Sunset at the Beach", w: 1440, h: 960 },
  { id: "mountain-dawn", src: "/photos/mountain-dawn.webp", label: "Mountains at Dawn", w: 1440, h: 960 },
  { id: "desert-dunes", src: "/photos/desert-dunes.webp", label: "Desert Dunes", w: 1440, h: 960 },
  { id: "forest-path", src: "/photos/forest-path.webp", label: "Path Through the Woods", w: 960, h: 1440 },
  { id: "lake-mirror", src: "/photos/lake-mirror.webp", label: "Still Lake", w: 1440, h: 960 },
  { id: "rolling-hills", src: "/photos/rolling-hills.webp", label: "Rolling Hills", w: 1440, h: 960 },
  { id: "coastal-cliffs", src: "/photos/coastal-cliffs.webp", label: "Coastal Cliffs", w: 1440, h: 960 },
  { id: "snow-peaks", src: "/photos/snow-peaks.webp", label: "Snowy Peaks", w: 1440, h: 960 },
  { id: "autumn-woods", src: "/photos/autumn-woods.webp", label: "Autumn Woods", w: 1440, h: 960 },
  { id: "river-bend", src: "/photos/river-bend.webp", label: "Bend in the River", w: 960, h: 1440 },
  { id: "canyon", src: "/photos/canyon.webp", label: "Red Canyon", w: 1440, h: 960 },
  { id: "wildflower-meadow", src: "/photos/wildflower-meadow.webp", label: "Wildflower Meadow", w: 1440, h: 960 },
  { id: "pine-fog", src: "/photos/pine-fog.webp", label: "Pines in the Fog", w: 1440, h: 960 },
  { id: "tropical-beach", src: "/photos/tropical-beach.webp", label: "Palm Trees", w: 1440, h: 960 },
  { id: "starry-night", src: "/photos/starry-night.webp", label: "Starry Night", w: 1440, h: 960 },
  { id: "aurora", src: "/photos/aurora.webp", label: "Northern Lights", w: 1440, h: 960 },
  { id: "storm-clouds", src: "/photos/storm-clouds.webp", label: "Storm Coming In", w: 1440, h: 960 },
  { id: "rainbow", src: "/photos/rainbow.webp", label: "Rainbow After Rain", w: 1440, h: 960 },
  { id: "misty-morning", src: "/photos/misty-morning.webp", label: "Misty Morning", w: 1440, h: 960 },
  { id: "full-moon", src: "/photos/full-moon.webp", label: "Full Moon", w: 1440, h: 960 },
  { id: "city-dusk", src: "/photos/city-dusk.webp", label: "City at Dusk", w: 1440, h: 960 },
  { id: "bridge-night", src: "/photos/bridge-night.webp", label: "Bridge at Night", w: 1440, h: 960 },
  { id: "street-golden", src: "/photos/street-golden.webp", label: "Golden Hour Street", w: 1440, h: 960 },
  { id: "rooftops", src: "/photos/rooftops.webp", label: "Rooftops", w: 1440, h: 960 },
  { id: "harbour", src: "/photos/harbour.webp", label: "Boats in the Harbour", w: 1440, h: 960 },
  { id: "train-station", src: "/photos/train-station.webp", label: "Train Station", w: 1440, h: 960 },
  { id: "neon-street", src: "/photos/neon-street.webp", label: "Neon Street", w: 1440, h: 960 },
  { id: "single-flower", src: "/photos/single-flower.webp", label: "Sunflower", w: 1200, h: 1200 },
  { id: "leaves", src: "/photos/leaves.webp", label: "Green Leaves", w: 1440, h: 960 },
  { id: "cactus", src: "/photos/cactus.webp", label: "Cactus at Sunset", w: 960, h: 1440 },
  { id: "mushrooms", src: "/photos/mushrooms.webp", label: "Toadstools", w: 1440, h: 960 },
  { id: "succulents", src: "/photos/succulents.webp", label: "Succulents", w: 1200, h: 1200 },
  { id: "autumn-leaf", src: "/photos/autumn-leaf.webp", label: "A Single Leaf", w: 1200, h: 1200 },
  { id: "dandelion", src: "/photos/dandelion.webp", label: "Dandelion Seeds", w: 1440, h: 960 },
  { id: "coffee-cup", src: "/photos/coffee-cup.webp", label: "Morning Coffee", w: 1200, h: 1200 },
  { id: "bookshelf", src: "/photos/bookshelf.webp", label: "Bookshelf", w: 1440, h: 960 },
  { id: "windowsill-plant", src: "/photos/windowsill-plant.webp", label: "Plant on the Windowsill", w: 960, h: 1440 },
  { id: "breakfast-table", src: "/photos/breakfast-table.webp", label: "Breakfast", w: 1440, h: 960 },
  { id: "teapot", src: "/photos/teapot.webp", label: "Teapot", w: 1440, h: 960 },
  { id: "candle", src: "/photos/candle.webp", label: "Candlelight", w: 960, h: 1440 },
  { id: "fruit-bowl", src: "/photos/fruit-bowl.webp", label: "Bowl of Fruit", w: 1440, h: 960 },
  { id: "desk", src: "/photos/desk.webp", label: "My Desk", w: 1440, h: 960 },
  { id: "bird-branch", src: "/photos/bird-branch.webp", label: "Bird on a Branch", w: 1440, h: 960 },
  { id: "cat-sleeping", src: "/photos/cat-sleeping.webp", label: "Cat Asleep", w: 1440, h: 960 },
  { id: "dog-field", src: "/photos/dog-field.webp", label: "Dog in the Field", w: 1440, h: 960 },
  { id: "fish", src: "/photos/fish.webp", label: "Koi Pond", w: 1440, h: 960 },
  { id: "butterfly", src: "/photos/butterfly.webp", label: "Butterfly", w: 1440, h: 960 },
  { id: "gradient-mesh", src: "/photos/gradient-mesh.webp", label: "Color Study", w: 1440, h: 960 },
  { id: "concentric", src: "/photos/concentric.webp", label: "Rings", w: 1200, h: 1200 },
  { id: "geo-tiles", src: "/photos/geo-tiles.webp", label: "Tile Pattern", w: 1200, h: 1200 },
  { id: "wave-lines", src: "/photos/wave-lines.webp", label: "Wave Lines", w: 1440, h: 960 },
  { id: "terrazzo", src: "/photos/terrazzo.webp", label: "Terrazzo", w: 1200, h: 1200 },
];

export const photoSrc = (id: string) =>
  PHOTO_ASSETS.find((p) => p.id === id)?.src ?? PHOTO_ASSETS[0].src;
