// Generated by scripts/generate-photos.mjs — do not edit by hand.

export interface SiteArt {
  /** Basename, no extension. */
  id: string;
  src: string;
  /** Alt text. Empty string means the picture is decorative.  */
  label: string;
  w: number;
  h: number;
}

export const SITE_ART: SiteArt[] = [
  { id: "avatar-alex", src: "/site/avatar-alex.webp", label: "Alex", w: 400, h: 400 },
  { id: "avatar-jordan", src: "/site/avatar-jordan.webp", label: "Jordan", w: 400, h: 400 },
  { id: "avatar-sam", src: "/site/avatar-sam.webp", label: "Sam", w: 400, h: 400 },
  { id: "avatar-grandma", src: "/site/avatar-grandma.webp", label: "Grandma", w: 400, h: 400 },
  { id: "avatar-doggo", src: "/site/avatar-doggo.webp", label: "Doggo", w: 400, h: 400 },
  { id: "product-laptop", src: "/site/product-laptop.webp", label: "Laptop", w: 900, h: 600 },
  { id: "product-tablet", src: "/site/product-tablet.webp", label: "Tablet", w: 900, h: 600 },
  { id: "product-phone", src: "/site/product-phone.webp", label: "Phone", w: 900, h: 600 },
  { id: "product-headphones", src: "/site/product-headphones.webp", label: "Headphones", w: 900, h: 600 },
  { id: "apple-pie", src: "/site/apple-pie.webp", label: "Apple pie", w: 900, h: 600 },
  { id: "soup-bowl", src: "/site/soup-bowl.webp", label: "Bowl of soup", w: 900, h: 600 },
  { id: "tomato-plant", src: "/site/tomato-plant.webp", label: "Tomato plant", w: 900, h: 600 },
  { id: "city-bus", src: "/site/city-bus.webp", label: "City bus", w: 900, h: 600 },
  { id: "cover-garden", src: "/site/cover-garden.webp", label: "The Maplewood Gardener", w: 420, h: 620 },
  { id: "cover-computer", src: "/site/cover-computer.webp", label: "Understanding Your Computer", w: 420, h: 620 },
  { id: "cover-soup", src: "/site/cover-soup.webp", label: "101 Soup Recipes", w: 420, h: 620 },
  { id: "cover-walks", src: "/site/cover-walks.webp", label: "Walks Around the World", w: 420, h: 620 },
];

export const siteArt = (id: string) =>
  SITE_ART.find((a) => a.id === id)?.src ?? SITE_ART[0].src;
